# Generated by Django 2.2.16 on 2024-01-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20240104_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='email',
            new_name='email_primary',
        ),
        migrations.AddField(
            model_name='information',
            name='email_secondary',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
